import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Admin',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Aibek',
      email: 'aibek@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    }
  ],
  products: [
    {
      // _id: '1',
      name: 'The Creature Choir',
      slug: 'the-creature-choir',
      category: 'Storybook',
      image: '/images/book_1.jpeg', 
      price: 12,
      countInStock: 5,
      author: 'David Walliams',
      rating: 0,
      numReviews: 0,
      description: 'Sing your heart out with a whole choir of characters, in the showstopping new picture book from number one bestselling author David Walliams',
    },
    {
      // _id: '2',
      name: 'Olive, Again',
      slug: 'olive-again',
      category: 'Contemporary Fiction',
      image: '/images/book_2.jpeg',
      price: 8,
      countInStock: 4,
      author: 'Elizabeth Strout',
      rating: 0,
      numReviews: 0,
      description: 'An extraordinary new novel by the Pulitzer Prize-winning, Number One New York Times bestselling author of Olive Kitteridge and My Name is Lucy Barton...',
    },
    {
      // _id: '3',
      name: 'Stanley Elwin & Alisdair Gray',
      slug: 'stanley-gray',
      category: 'Contemporary Fiction',
      image: '/images/book_6.jpeg',
      price: 7,
      countInStock: 0,
      author: 'Alex Styles',
      rating: 0,
      numReviews: 0,
      description: "Arthur M. Saltzman, Stanley Elkin: An Introduction\/Peter J. Bailey, 'A Hat Where There Never Was a Hat': Stanley Elkin's Fifteenth Interview\/Stanley Elkin, Words and Music\/William Gass, Stanley Elkin: An Anecdote\/Jerome Charyn...",
    },
    {
      // _id: '4',
      name: 'The Rule of the Land',
      slug: 'rule-of-land',
      category: 'History',
      image: '/images/book_7.jpeg',
      price: 13,
      countInStock: 8,
      author: 'Garrett Carr',
      rating: 0,
      numReviews: 0,
      description: "In the wake of the EU referendum, the United Kingdom's border with Ireland has gained greater significance: it is set to become the frontier with the European Union. Over the past year, Garrett Carr has travelled this border...",
    },
    {
      // _id: '4',
      name: 'The Story of the Holy Land',
      slug: 'holy-land',
      category: 'History',
      image: '/images/book_8.jpeg',
      price: 11,
      countInStock: 5,
      author: 'Peter Walker',
      rating: 0,
      numReviews: 0,
      description: "In the wake of the EU referendum, the United Kingdom's border with Ireland has gained greater significance: it is set to become the frontier with the European Union. Over the past year, Garrett Carr has travelled this border...",
    },
    {
      // _id: '4',
      name: 'Doctor Who',
      slug: 'doctor-who',
      category: 'Storybook',
      image: '/images/book_9.jpeg',
      price: 4,
      countInStock: 2,
      author: 'Colins Baker',
      rating: 0,
      numReviews: 0,
      description: "In this exciting collection you'll find all-new stories spinning off from some of your favourite Doctor Who moments across the history of the series. Learn what happened next, what went on before...",
    },
  ],
};
export default data;
